# Generated by Django 4.1.8 on 2023-05-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotecim', '0003_usuario_fecha_hora_fin_usuario_fecha_hora_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='id_estacion',
            new_name='estacion',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
