# Generated by Django 4.1.8 on 2023-05-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotecim', '0004_rename_id_estacion_reserva_estacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estaciondetrabajo',
            name='disponibilidad',
            field=models.BooleanField(default=False),
        ),
    ]
