# Generated by Django 5.0.1 on 2024-02-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotecim', '0008_remove_posicion_id_estacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicion',
            name='coordenadas',
        ),
        migrations.AddField(
            model_name='posicion',
            name='coordenada_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posicion',
            name='coordenada_r',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posicion',
            name='coordenada_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posicion',
            name='coordenada_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posicion',
            name='coordenada_z',
            field=models.IntegerField(default=0),
        ),
    ]
