# Generated by Django 4.1.8 on 2023-05-26 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionDeTrabajo',
            fields=[
                ('id_estacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('disponibilidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PosicionRutina',
            fields=[
                ('id_posicion_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('coordenadas', models.CharField(max_length=255)),
                ('orden', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('id_estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.estaciondetrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('id_webcam', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('id_estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.estaciondetrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='RutinaPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_posicion_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.posicionrutina')),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('id_estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.estaciondetrabajo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='posicionrutina',
            name='id_rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.rutina'),
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id_posicion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_posicion', models.CharField(max_length=255)),
                ('coordenadas', models.CharField(max_length=255)),
                ('id_estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.estaciondetrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoreoWebcam',
            fields=[
                ('id_monitoreo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('id_estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.estaciondetrabajo')),
                ('id_webcam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.webcam')),
            ],
        ),
        migrations.CreateModel(
            name='EstacionWebcam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.estaciondetrabajo')),
                ('id_webcam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.webcam')),
            ],
        ),
        migrations.CreateModel(
            name='EstacionRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.estaciondetrabajo')),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id_comando', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('orden', models.CharField(max_length=255)),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotecim.rutina')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rutinaposicion',
            constraint=models.UniqueConstraint(fields=('id_rutina', 'id_posicion_rutina'), name='unique_rutina_posicion'),
        ),
        migrations.AddConstraint(
            model_name='estacionwebcam',
            constraint=models.UniqueConstraint(fields=('id_estacion', 'id_webcam'), name='unique_estacion_webcam'),
        ),
        migrations.AddConstraint(
            model_name='estacionrutina',
            constraint=models.UniqueConstraint(fields=('id_estacion', 'id_rutina'), name='unique_estacion_rutina'),
        ),
    ]
