# Generated by Django 4.1.8 on 2023-05-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotecim', '0002_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_hora_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
