# Generated by Django 4.2.4 on 2024-01-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotecim', '0008_remove_posicion_id_estacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_posicion', models.CharField(max_length=255)),
                ('coordenada_x', models.FloatField()),
                ('coordenada_y', models.FloatField()),
                ('coordenada_z', models.FloatField()),
                ('coordenada_r', models.FloatField()),
                ('coordenada_p', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Posicion',
        ),
    ]
